Vishruth-S/CompetitiveCode

Hackerrank_problems/kangaroo/solution2.cpp
Added Kangaroo C++ solution ` solution2.cpp ` to ` Hackerrank_problems/kangaroo `
=> Added Kangaroo C++ solution 

Hackerrank_problems/Solve_me_first/Problem.md, Hackerrank_problems/Solve_me_first/solution.java
Added java problem and solution from hackerrank
=> added_solve_me_first

LeetCode_problems/Spiral Matrix/problem.md, LeetCode_problems/Spiral Matrix/solution.py
=> Added Spiral Matrix problem and solution from LeetCode

Hackerrank_problems/3D_Surface_Area/Problem.md, Hackerrank_problems/3D_Surface_Area/solution.cpp
=> Solution for HackerRank probelm 3D Surface Area

Hackerrank_problems/Bigger is Greater/BiggerIsGreater.java, Hackerrank_problems/Bigger is Greater/README.md
Added a medium difficulty problem called BiggerIsGreater to the Hackerrank folder with a java solution for it.
=> Added BiggerIsGreater problem

Misc/HiveMaker/HikeMaker.md, Misc/HiveMaker/HikeMaver.md
I cannot put solution.py currently, but once this is approved, I can make it right away. Please approve! Thank you!
=> Created Misc folder and HiveMaker

CodeSignal_problems/AdjacentElementsProduct/Problem.md, CodeSignal_problems/AdjacentElementsProduct/solution.js
The solution is done using javascript
=> Adjacent elements product

Contributing.md, Misc/HiveMaker/HikeMaver.md
I've fixed very trivial typo in Contributing.md & HiveMaver.md.
=> fixed typo

Hackerrank_problems/Sequence_Equation/problem.md, Hackerrank_problems/Sequence_Equation/solution.cpp
I have added the detailed problem explanation and cpp solution for Sequence Equation
- HackerRank Problems/SequenceEquation /problem.md
- HackerRank Problems/SequenceEquation /solution.cpp
=> Sequence Equation (added detailed explanation in problem.md and solution.cpp) 

Hackerrank_problems/Sequence_Equation/Problem.md, Hackerrank_problems/Sequence_Equation/Solution.java
=> Added java solution for sequence equation problem

Misc/HiveMaker/solution_1.py
A solution for the HiveMaker problem. Recursion could also be used I think.
=> Solution for HiveMaker

Hackerrank_problems/Non_divisible_Subset/problem.md, Hackerrank_problems/Non_divisible_Subset/solution.cpp
Hello ! My name is  Rajvir Singh . My email is rajvirsinghfeb16@gmail.com
The problem submitted by me is one of those implementation dominating problems which anyone can solve provided they are not underestimating the impact of basic mathematics in competitive programming. 
My solution is kind of self explaining the logic and will be easily understood if the person follows the comments along with the code. They will realize the use and purpose of each data structure. 
Also a big thank you to this repository to help us look up for varied and diverse solutions to problems in many websites. 
Thank you
=> added a hackerrank problem and its solution

CodeChef_problems/AEIOUHW/problem.md, CodeChef_problems/AEIOUHW/solution.md
=> Added a CodeChef problem!

Hackerrank_problems/Day_Of_The_Programmer/solution.rb
implementation of day of programmer in ruby
=> day of programmer solution ruby

CodeChef_problems/A Problem on Sticks/problem.md
Created a New problem From CodeChef Problem Set
=> Created a new Problem in CodeChef Dir problem.md

CodeChef_problems/KJCP02/problem.md, CodeChef_problems/KJCP02/solution.cpp
Add problem **Second Year Pains** from CodeChef.
=> Added KJCP02

Hackerrank_problems/Triangle_Quest/problem.md, Hackerrank_problems/Triangle_Quest/solution.py
Added problem and solution in python for triangle_quest (required to be 2 lines or less).
=> Karlmarx triangle quest

CodeChef_problems/uncle_jhony/problem.md, CodeChef_problems/uncle_jhony/solution.py
Please Merge my PR For the solution to the CodeChef problem Uncle Jhony in python. It's the PR for the issue #49 . Please Merge it.
=> added solution to the codechef problem of Uncle Jhony in python

Hackerrank_problems/BeautifulDaysAtTheMovies/problem.md, Hackerrank_problems/BeautifulDaysAtTheMovies/solution.py
Added problem and solution to Beautiful days At The Movies.
=> Beautiful days At The Movies

Hackerrank_problems/Migratory Birds/problem.md, Hackerrank_problems/Migratory Birds/solution.py
I have added solutions of Migratory Bird of Hackerrank platform please review it.
=> Added Migratory birds in python Hackerrank

Hackerrank_problems/Write a Function- Is this Leap Year/problem.md, Hackerrank_problems/Write a Function- Is this Leap Year/solution.py
Added the HackerRank problem and its solution in Python. It passed all the test cases on HackerRank.
=> Added the HackerRank problem and its solution in Python

LeetCode_problems/Median_of_two_sorted_array/code.cpp, LeetCode_problems/Median_of_two_sorted_array/problem.md, LeetCode_problems/Median_of_two_sorted_array/solution.txt
In accordance to issue #80 
Problem Name : 4. Median of Two Sorted Arrays
link: https://leetcode.com/problems/median-of-two-sorted-arrays/
Difficulty: Hard
Problem.md contains the explaination of the problem.
Code.cpp and solution.txt contains solution in both text and cpp format.
=> 0004 added

Hackerrank_problems/Maximize_It!/problem.md, Hackerrank_problems/Maximize_It!/solution.py
Adding new problem in HackerRank Problem Set.
=> Adding new problem in HackerRank PS

Hackerrank_problems/Divisible Sum Pairs/problem.md, Hackerrank_problems/Divisible Sum Pairs/solution.cpp
I have added the solutions of **_Divisible Sum Pairs_** of **HackerRank** platform. Please review it.
=> Added Divisible Sum Pairs in CPP HackerRank

LeetCode_problems/Majority Element/problem.md, LeetCode_problems/Majority Element/solution1.py
I have solved Majority element question (easy) in python language and added. Please review it.
=> Added leetcode Majority Element

CodeChef_problems/CARSELL/problem.md, CodeChef_problems/CARSELL/solution.cpp
=> Added the CARSELL problem from CodeChef

CodeChef_problems/CHEFWED/Solution.py
solution of CHEFWED problem in Python
=> Added  Solution.py for CHEFWED

LeetCode_problems/Wildcard_Matching/problem.md, LeetCode_problems/Wildcard_Matching/solution.py
Added problem readme file and solution py file in the respective directory structure created.
=> Added wildcard pattern matching python program

CodeChef_problems/FINXOR/problem.md, CodeChef_problems/FINXOR/solution.cpp
Added solution for the problem Find XOR on CodeChef.
**Language** - C++
=> Added Solution for the Problem FINXOR

LeetCode_problems/Unique Paths II/problem.md, LeetCode_problems/Unique Paths II/solution1.cpp
=> Added solution for Unique Paths II

LeetCode_problems/First Missing Positive/problem.md, LeetCode_problems/First Missing Positive/solution.py
Hi @Vishruth-S,
I have added a leetcode Hard problem with description, frequently asked in the interviews.
I have properly drafted the solution as per contributing guidelines. Please do check
Thanks,
Shubhakar
=> LeetcodeProblem | Hard| Added

LeetCode_problems/Monotonic Array/problem.md, LeetCode_problems/Monotonic Array/solution_1.py
I have solved leetcode monotonic array in Python. Please review it.
=> Leetcode Monotonic Array solution python.

LeetCode_problems/Maximum Sum Circular Subarray/problem.md, LeetCode_problems/Maximum Sum Circular Subarray/solution.cpp
This is a variation of the Maximum subarray sum i.e kadane's algorithm. Written Pseudocode and commented well.
=> Leetcode Maximum sum circular subarray || Sanjay235

CodeChef_problems/Ada King/problem.md, CodeChef_problems/Ada King/solution.cpp
Added a CodeChef problem Ada King
Files added
-  CodeChef/ Ada King/ problem.md
- CodeChef/Ada King/ solution.cpp
=> Ada King codechef

CodeChef_problems/CVDRUN/problem.md, CodeChef_problems/CVDRUN/solution.cpp
The pull request contains the solution to October Challenge CovidRun in C++ language
=> COVID RUN CodeChef

Hackerrank_problems/Pairs/problem.md, Hackerrank_problems/Pairs/solution.cpp, LeetCode_problems/Majority Element/solution2.cpp
Added an alternate solution to majority element which is space-optimized and Added pairs from hackerrank
=> Majority Element in O(1) Space Leetcode & Pairs Hacker-rank

LeetCode_problems/Compare Version Numbers/problem.md, LeetCode_problems/Compare Version Numbers/solution.cpp
This is a well know problem for comparing two versions of a software solution.
=> Comparing version numbers | Sanjay235

Hackerrank_problems/MinimumHeightOFTriangle/problem.md, Hackerrank_problems/MinimumHeightOFTriangle/solution.py
I already have repo with solution of hacker rank problems [here](https://github.com/AzadKshitij/Hacker-Rank)
=> [NEW] Add Minimum height of triangle solution

Hackerrank_problems/Arithmetic Operators/problem.md, Hackerrank_problems/Arithmetic Operators/solution.py
Added required documentation and new problem folder in Hackerrank directory.
=> Added hackerrank problem Arithmetic Operators in Python

Hackerrank_problems/counting_valleys/Solution.java
Added Java solution and explanation for CountingValleys
=> Added Java solution and explanation for CountingValleys

Hackerrank_problems/Recursion_Fibonacci_Numbers/problem.md, Hackerrank_problems/Recursion_Fibonacci_Numbers/solution.py
Adding a solution to HackerRank's Recursion: Fibonacci Numbers problem.
=> Add fibonacci recursive

CodeChef_Problems/Chef and Card game/problem.md, CodeChef_Problems/Chef and Card game/solution.py
Added solution for codechef problem chef and card game from july challenge 2020,  in python language. under the issue #49 
##changes made:
Added codechef_problems folder
created chef and cared game folder under codechef_problems
created problem.md and solution.py under chef and card game folder
=> chef and card game from codechef

LeetCode_problems/Combination Sum.py, LeetCode_problems/Remove Duplicates from Sorted List/Problem.md, LeetCode_problems/Remove Duplicates from Sorted List/Solution
Runtime: 40 ms, faster than 99.67% of Python3 online submissions for Combination Sum. 
Memory Usage: 14.1 MB, less than 14.23% of Python3 online submissions for Combination Sum.
=> Combination Sum (Problem number 39)

Hackerrank_problems/Fibonacci-Series/Solution.py, Hackerrank_problems/Fibonacci-Series/problem.md
added a hackerrank problem and solution in python
=> Fibonacci-Series

LeetCode_problems/Count Square Submatrices with All Ones/problem.md, LeetCode_problems/Count Square Submatrices with All Ones/solution.java
Added java code for the question: 'Count Square Submatrices with All Ones'
=> Leetcode question 

LeetCode_problems/Linked List Components/problem.md, LeetCode_problems/Linked List Components/solution.cpp, LeetCode_problems/Remove Nth Node from End/problem.md, LeetCode_problems/Remove Nth Node from End/solution.cpp, LeetCode_problems/Reorder_List/problem.md, LeetCode_problems/Reorder_List/solution.cpp
I have added 3 Q of linked list from leetcode of medium level.
The following files have been added 
-  Leetcode Problems/Reorder_List/problem.md
-  Leetocde Problems/Reorder_List/solution.cpp
-  Leetcode Problems/Linked List Components/problem.md
-  Leetocde Problems/Linked List Components/solution.cpp
-  Leetcode Problems/Remove Nth node from end/problem.md
-  Leetocde Problems/Remove Nth node from end/solution.cpp
=> Added 3 medium Linked LIst Leetcode Questions

LeetCode_problems/Container With Most Water/Solution.java, LeetCode_problems/Container With Most Water/problem.md
Problem no 11 Container With Most Water solution in java
=> Leetcode problem added

LeetCode_problems/Gas Station/problem.md, LeetCode_problems/Gas Station/solution.cpp
Added gas station problem from leetcode.
=> Gas station problem | Sanjay235

LeetCode_problems/Remove Covered Intervals/Solution.java, LeetCode_problems/Remove Covered Intervals/problem.md
Added the solution to the leetcode #1288 "Covered interval problem" in java
=> Added leetcode covered interval problem in java

LeetCode_problems/Add Strings/Solution.py, LeetCode_problems/Add Strings/problem.md, LeetCode_problems/add-binary/Solution.py, LeetCode_problems/add-binary/problem.md, LeetCode_problems/count-good-triplets/Solution.py, LeetCode_problems/count-good-triplets/problem.md, LeetCode_problems/insert-into-a-binary-search-tree/Add Strings/Solution.py, LeetCode_problems/insert-into-a-binary-search-tree/Add Strings/problem.md, LeetCode_problems/range-sum-of-bst/Solution.py, LeetCode_problems/range-sum-of-bst/problem.md
Added 5 leetcode Problems:
- add-binary
- add strings
- count-good-triplets
- insert-into-a-binary-search
- range of sum-bst
=> Added Leetcode Problems

LeetCode_problems/K Closest Points to Origin/Problem.md, LeetCode_problems/K Closest Points to Origin/Solution.java
Added K closest points to the origin
=> Added LC question

LeetCode_problems/Minimum Path Sum/Solution.java, LeetCode_problems/Minimum Path Sum/problem.md
Added the leetcode question 64 minimum path sum in java
=> Added leetcode #64 minimum path sum in java

Hackerrank_problems/CreditCardValid/problem.md, Hackerrank_problems/CreditCardValid/solution.py
This PR contains the code for the credit card validity check program from Hackerrank
=> credit card problem stable working

LeetCode_problems/Anagrams/Solution.java, LeetCode_problems/Anagrams/problem.md
Added leetcode #49 Anagrams in java
=> Added leetcode #49 Anagrams in java

LeetCode_problems/Search Rotated Sorted Array/Solution.java, LeetCode_problems/Search Rotated Sorted Array/problem.md
Added Leetcode problem 33 search rotated sorted array in java
=> Added Leetcode problem 33 search rotated sorted array in java

LeetCode_problems/Insert Interval/problem.md, LeetCode_problems/Insert Interval/solution.cpp
Adding Insert interval problem to the Leetcode problems.
=> Insert interval | Sanjay235

Codeforces_problems/RockPaperScissors/problem.md, Codeforces_problems/RockPaperScissors/solution.cpp
- Codeforces directory added
- new problem added
=> Added new problem set for Codeforces

Hackerrank_problems/Birthday_chocolate/problem.md, Hackerrank_problems/Birthday_chocolate/solution.py, Hackerrank_problems/kangaroo/solution3.py
As you suggested in last PR complete **explanation** of **logic** Thanks.
=> [NEW] Add Birthday Chocolate solution

Hackerrank_problems/Chocolate Feast/problem.md, Hackerrank_problems/Chocolate Feast/solution.cpp
I have added the solution of **_Chocolate Feast_** problem of **HackerRank** platform with proper indentation and gave the necessary explanation of the logic. Please review it.
=> Added Chocolate Feast in CPP HackerRank 

Misc/Caesar_Cipher_Encryptor/problem.md, Misc/Caesar_Cipher_Encryptor/solution.py
Hi, kindly check if this is eligable for a PR.
=> Add Caesar Cipher Encryptor

LeetCode_problems/Possible Bipartition/Problem.md, LeetCode_problems/Possible Bipartition/Solution.java
=> Added Bipartition prob LC

LeetCode_problems/Winner of an Array Game/Solution.py, LeetCode_problems/Winner of an Array Game/readme.md
Hi @Vishruth-S,
I have added a leetcode medium problem with proper explanation
Thanks,
Shubhakar
=> [Leetcode] Medium Problem with explanation

Hackerrank_problems/ElectronicShop/solution2.py
Added alternative solution for the electronics shop problem of Hackerrank.
=> Add solution2.py for Electronic_shop(Hackerank_problems)

LeetCode_problems/Rotate Image/problem.md, LeetCode_problems/Rotate Image/solution.js
=>  new leetcode problem and javascript solution

LeetCode_problems/Find_the_Difference/problem.md, LeetCode_problems/Find_the_Difference/solution.py
code with comments for explaination
=> added LeetCode_problems/Find_the_Difference

LeetCode_problems/Length of Last Word/problem.md, LeetCode_problems/Length of Last Word/solution.cpp
The following contains the problem link and a detailed solution to the problem Length of last word.
=> Length of last word

Hackerrank_problems/Time_Conversion/problem.md, Hackerrank_problems/Time_Conversion/time_conversion.py
Added implementation for a Hackerrank Problem `Time Conversion`
@Vishruth-S Please merge this PR.
=> Added problem nd solution for time_conversion

LeetCode_problems/Maximum Product Subarray/problem.md, LeetCode_problems/Maximum Product Subarray/solution.py
Added the solution in python for the Problem Leetcode - 152: Maximum Product Subarray
Difficulty: Medium
@Vishruth-S
Kindly take a look at my PR. I have adhered to the specified guidelines in Contributing.md. 😄
=> Added solution for Maximum Product Subarray - Leetcode - Python

InterviewBit_problems/Stack and Queues/Largest Rectangle in Histogram/problem.md, InterviewBit_problems/Stack and Queues/Largest Rectangle in Histogram/solution.cpp
Problem link: https://www.interviewbit.com/problems/largest-rectangle-in-histogram/
Adhered to contributing guidelines.
Hope you accept and tag it.
=> Added InterviewBit problem with solution in cpp

LeetCode_problems/Queue Reconstruction by Height/Question.txt, LeetCode_problems/Queue Reconstruction by Height/Solution.cpp
Medium level leetcode question. Question link in read-me file, along with C++ solution and description.
=> Leetcode question added

Codeforces_problems/Fence/problem.md, Codeforces_problems/Fence/solutions.cpp, Codeforces_problems/Subset Mex/problem.md, Codeforces_problems/Subset Mex/solutions.cpp
=>  added problem solution Subset Mex and Fence with logic

Hackerrank_problems/Service Lane/problem.md, Hackerrank_problems/Service Lane/solution.c
Link to Problem: https://www.hackerrank.com/challenges/service-lane/problem
Link to Solution: https://www.hackerrank.com/challenges/service-lane/submissions/code/162876265
=> Service Lane

Codeforces_problems/Kevin and Grid/problem.md, Codeforces_problems/Kevin and Grid/solution.cpp
Hi @Vishruth-S,
I have added a Div-1 problem from codeforces.
Thanks,
Shubhakar
=> [Codeforces] Div1 Problem added

LeetCode_problems/Array Partition 1/problem.md, LeetCode_problems/Array Partition 1/solution(1).py
I have solved Array Partition problem of leetcode in Python. Please review it.
=> Add Array Partition leetcode

Codeforces_problems/TurnTheRectangles/problem.md, Codeforces_problems/TurnTheRectangles/solution.cpp
I have added a codeforces problem
=> Added Codeforces 234626 Problem E

Hackerrank_problems/Number Line Jumps/problem.md, Hackerrank_problems/Number Line Jumps/solution.py
=> I have added the kangaroo jump problem and its solution 

LeetCode_problems/kth_factor_of_n/Problem.md, LeetCode_problems/kth_factor_of_n/solution.py
Added a new problem and solution to the leetcode_problems folder. The problem is to find the kth factor of a number n.
@Vishruth-S Please Merge my PR.
=> Added problem and solution to the leetcode problem for the Kth-factor-of-n

Hackerrank_problems/Compare The Triplets/compare_the_triplets.py, Hackerrank_problems/Compare The Triplets/problem.md
Added implementation for a Hackerrank Problem `Compare the Triplets`
@Vishruth-S Please merge this PR.
=> Added problem nd solution for compare-the-triplets

InterviewBit_problems/Sorting/Max NonNegative SubArray/problem.md, InterviewBit_problems/Sorting/Max NonNegative SubArray/solution.py
Adding another problem from Interview Bit which contains the python file to find the maximum non-negative subarray
=> Maximum Non Negative Subarray

CodeChef_problems/PPATTERN/PPATTERN.py, CodeChef_problems/PPATTERN/Problem.md
I had added a solution to an interesting pattern printing problem of CodeChef
@Vishruth-S #204 I had made the suggested changes
=> Added solution to CodeChef pattern printing Problem

Codeforces_problems/Dice Tower/problem.md, Codeforces_problems/Dice Tower/solution.cpp, Codeforces_problems/New Theatre Square/problem.md, Codeforces_problems/New Theatre Square/solution.cpp
Added Two problems from codeforces.
=> Added Two codeforces problem(Dice tower and New Theatre Square)

CSES_problems/Missing Number/problem.md, CSES_problems/Missing Number/solution.py, CSES_problems/Repetitions/problem.md, CSES_problems/Repetitions/solution.py
I have added a folder for CSES problems and also added two problem solutions in it.
=> cses problems added

CodeChef_problems/GCD operations/problem.md, CodeChef_problems/GCD operations/solution.cpp
Included problem and solution(cpp)
=> GCD operation problem from codechef sep lunch time

HackerEarth_problems/RepeatedKTimes/problem.md, HackerEarth_problems/RepeatedKTimes/solution.cpp
Added problem and solution file for the HackerEarth problem, "Repeated K Times"
=> Added HackerEarth Problem: Repeated K Times

project_euler_problems/digit factorials/problem.md, project_euler_problems/digit factorials/solution.cpp, project_euler_problems/integer right triangle/problem.md, project_euler_problems/integer right triangle/solution.cpp
Added a folder for project Euler
and added these two problems:
- integer right triangle
- digit factorials
=> Added project euler folder and 2 problem

LeetCode_problems/Insert Interval/InsertInterval.java
This is in reference to the previous PR #197.
I started fresh and have made all the required changes.
Please review them.
Thankyou.
=> Added Insert Interval in Java

LeetCode_problems/Number of Islands/problem.md, LeetCode_problems/Number of Islands/solution1.cpp
=> Added Number of Islands solution

CSES_Problems/Weird_Algorithm/Problem.md, CSES_Problems/Weird_Algorithm/solution.c
I have added a program of Weird Algorithm for CSES folder.
@Vishruth-S please merge my PR.
=> added problem and solution of weird algorithm

Misc/Fibonacci_Search/Problem.md, Misc/Fibonacci_Search/solution.java
=> Fibonacci search

HackerEarth_problems/New Friends/problem.md, HackerEarth_problems/New Friends/solution.cpp, HackerEarth_problems/Shubham and Subarray Xor/problem.md, HackerEarth_problems/Shubham and Subarray Xor/solution.cpp
Flow problem from hackerEarth. Implemented using dinic.
=> Added a HackerEarth Flow Problem

HackerEarth_problems/New Friends/problem.md, HackerEarth_problems/New Friends/solution.cpp, HackerEarth_problems/Shubham and Subarray Xor/problem.md, HackerEarth_problems/Shubham and Subarray Xor/solution.cpp
=> Added another HackerEarth problem

HackerEarth_problems/Grid/problem.md, HackerEarth_problems/Grid/solution.cpp
=> Added a HackerEarth Problem

CodeChef_problems/Minimum Insertions/problem.md, CodeChef_problems/Minimum Insertions/solution.cpp
An included problem from the September cook-off CodeChef with problem and solution(CPP) with an explanation
=> Minimun Insertions problem from codechef september cook off

CodeChef_problems/POSAND/problem.md, CodeChef_problems/POSAND/solution.cpp
@Vishruth-S  i made a PR, kindy review the same.
=> Add solution to POSAND problem Oct-challange

InterviewBit_problems/Sorting/Hotel Booking/problem.md, InterviewBit_problems/Sorting/Hotel Booking/solution.py
Adding another program in Python which will find out the N rooms available for the bookings in the Hotel
=> Hotel Booking

Codeforces_problems/Bargain/problem.md, Codeforces_problems/Bargain/solution.cpp
Included problem and solution(CPP) with an explanation.
=> codeforces problem from codeforces round#675

Codeforces_problems/Greg's Workout/problem.md, Codeforces_problems/Greg's Workout/solution.cpp
I have added the _solution_ of [Greg's Workout](https://codeforces.com/problemset/problem/255/A) problem of ***Codeforces***.
Gave the necessary explanation of the logic in the form of comments in the solution file. Also, the solution is well _indented_.
Please Review !
=> Added Greg's Workout of Codeforces in CPP

Misc/Caesar_Cipher_Encryptor/solution2
=> Added solution2 for Caeser-Encryptor

GeeksForGeeks/Kth_Smallest_Element/Problem.md, GeeksForGeeks/Kth_Smallest_Element/Solution.cpp
Finding the Kth Smallest Element by keeping a checking of the frequency of the inputted elements in a frequency array.
=> Added the problem and solution to the Kth Smallest Element

Hackerrank_problems/Time_In_Words/Problem.md, Hackerrank_problems/Time_In_Words/solution.cpp
hello sir @Vishruth-S , in this pull request i would like to add solution for hackerrank
This solution is written in cpp and just by using simple logic and vocab dictionary.
and it's pass all test from Hackerrank testcase
please kindly review this PR.. i would like to know any feedback from you.. thank you :smile:
=> feature(Hackerrank_problem): add Time In Words solution

GeeksForGeeks/Pallindrome String/solution2.py
Here is another solution to the palindrome string solution
=> Added solution2 for PalindromeString

CodeChef_problems/ELEVTR/problem.md, CodeChef_problems/ELEVTR/problem.txt, CodeChef_problems/ELEVTR/solution.cpp
Hey! I have added ELEVTR problem solution of CodeChef here. Please accept my PR  and help me to contribute in open source.
=> ELEVTR problem solution is added from codechef

CodeChef_problems/ANIRWO/solution2.cpp
solution to the codechef problem ANIRWO in cpp
=> solution2.cpp

Codeforces_problems/Cubes Sorting1420A/Solution.cpp, Codeforces_problems/Cubes Sorting1420A/problem.md
Codeforces Round 672, Div 2, Problem A.
=> Added a problem and solution in codeforces folder.

Codeforces_problems/Domino Piling/problem.md, Codeforces_problems/Domino Piling/solution.py, Codeforces_problems/Next Round/problem.md, Codeforces_problems/Next Round/solution.py, Codeforces_problems/Team/problem.md, Codeforces_problems/Team/solution.py, Codeforces_problems/Way too long words/problem.md, Codeforces_problems/Way too long words/solution.py
I have added some solutions to 800 rated codeforces problems with proper commenting. It can be helpful for anyone who has just stepped into the world of competitive programming
=> added some codeforces solutions

Hackerrank_problems/Max_Min/problem.md, Hackerrank_problems/Max_Min/solution.cpp
hello sir @Vishruth-S , i would like to add new hackerrank solution for medium Greedy Algorithm Hackerrank Problem [here](https://www.hackerrank.com/challenges/angry-children/problem).
I solved this problem with C++ by using only simple sort and find min max algorithm value in subArray.
and it pass all the test case in hackerrank
please kindly review this PR.. i would like to hear any feedback from you.. thank you :smiley:
=> feature(hackerrank): add Max Min hackerrank solution

Hackerrank_problems/Array Manipulation/Solution1.py
=> Solution in python

project_euler_problems/10001st prime/problem.md, project_euler_problems/10001st prime/solution.c, project_euler_problems/10001st prime/solution.js, project_euler_problems/10001st prime/solution.py, project_euler_problems/lattice paths/problem.md, project_euler_problems/lattice paths/solution.js, project_euler_problems/summation of primes/problem.md, project_euler_problems/summation of primes/solution.c, project_euler_problems/summation of primes/solution.js, project_euler_problems/summation of primes/solution.py
Add solutions for euler 7, 10 and 15
=> Add some euler problems solutions

Hackerrank_problems/loops/Solution1.py
problem solved written code with proper comment.
=> simple problem sloved

Hackerrank_problems/Solve_me_first/solve_me_first_solution2
problem solved written code with proper comment.
=> solve_me_first_solution2

Codeforces_problems/Dreamoon and WIFI/problem.md, Codeforces_problems/Dreamoon and WIFI/solution.cpp
I have added "Dreemoons and WIFI" problem from codeforces providing the problem link , its solutions and its logic idea
=> adding new problem from codeforces

Hackerrank_problems/diagonal-difference/problem.md, Hackerrank_problems/diagonal-difference/solution.cpp
hello sir @Vishruth-S , i would like to add new hackerrank solution for Algorithm diagonal - difference Problem here.
Please kindly review this PR.. i would like to hear any feedback from you.. Thanks 😁
=> Diagonal diffrence

Codeforces_problems/FloorNumber/problem.md, Codeforces_problems/FloorNumber/solution.cpp
=> add Floor Number

HackerEarth_problems/Odd one out/problem.md, HackerEarth_problems/Odd one out/solution.cpp
I've added a new problem from hackerearth, using c++ for the solution.
thanks in advance.
=> odd one out problem and solution from hackerearth.

Hackerrank_problems/Cycle Detection/problem.md, Hackerrank_problems/Cycle Detection/solution.py
I have added a new problem from Hackerrank: [Cycle detection](https://www.hackerrank.com/challenges/detect-whether-a-linked-list-contains-a-cycle/problem). The solution is in python, if you see something out of the standard here please let me know. Thanks in advance.
=> Add the cycle detection problem from Hackerrank

Codeforces_problems/sum of digits/problem.md, Codeforces_problems/sum of digits/solution.cpp
I have added a new problem from codeforces and I implemented it using cpp and discussed its logic idea, could you please check it?
thanks in advance!
=> solving codeforces problem level-B

Codeforces_problems/Telephone Number 1167A/problem.md, Codeforces_problems/Telephone Number 1167A/solution.cpp
I have added "Telephone Number - 1167A" problem from codeforces. It has the problem link, solution, and logic explained.
=> Added new codeforces problem

LeetCode_problems/Add Strings/solution.cpp
Added code in CPP with Description
=> Added Solution for CPP with Description

Codeforces_problems/Barrels/problem.md, Codeforces_problems/Barrels/soultion.cpp, Codeforces_problems/decoding/problem.md, Codeforces_problems/decoding/solution.cpp
I have added a new problem from codeforces and I implemented it using cpp and discussed its logic idea, could you please check it?
thanks in advance!
=> solving decoding string problem

Codeforces_problems/Drazil and Factorial/problem.md, Codeforces_problems/Drazil and Factorial/solution.cpp
I have added a new greedy problem from codeforces, I have implemented it in c++ and discussed its logic idea, could you please check it?
thanks in advance
=> adding new codeforces problem

HackerEarth_problems/Xenny and Partially Sorted Strings/problem.md, HackerEarth_problems/Xenny and Partially Sorted Strings/solution.py
=> Adding a new Hackerearth problem and solution

Hackerrank_problems/Hotel Price/problem.md, Hackerrank_problems/Hotel Price/solution.cpp
hello sir @Vishruth-S , I would like to add new hackerRank solution for Algorithm Hotel Price Problem here.
Please kindly check my work Sir 
Thank you😁
=> Hotel price

Codeforces_problems/Young Physicist/problem.md, Codeforces_problems/Young Physicist/solution.py
=> Young Physicist in Codeforces_Problems

USEFUL_RESOURCES.md
This can be very helpful for 
* Track your progress
* How you stand against your friends and top competitive coders
* Unified ToDo list to upsolve problems
* Upcoming contest and reminders
* other small useful utilities
=> Updated USEFUL_RESOURCES.md

Codeforces_problems/Numbers on Whiteboard/problem.md, Codeforces_problems/Numbers on Whiteboard/solution.cpp
=> Added solution for codeforces problem - Numbers on whiteboard

Hackerrank_problems/Find_a_point/problem.md, Hackerrank_problems/Find_a_point/solution.py
=> add code to solve find point

CodeChef_problems/CSUM/problem.md, CodeChef_problems/CSUM/solution.cpp
- [X ] My Pull Request adheres to the Contribution guidelines.
(Only completed checklist PRs will be reviewed)   
hello @Vishruth-S , i'm back again :smile: . 
now i came with code chef CSUM solution
it already pass all test case from codechef
please kindly review this PR.. i would like to receive any feedback from you.. Thank you :smile: :pray:
=> feature(codeChef): add codeChef solution for CSUM problem

Hackerrank_problems/Maximum_draws/problem.md, Hackerrank_problems/Maximum_draws/solution.py
=> add solution for maximum draws

project_euler_problems/integer right triangle/solution.py
=> Project euler solution in python

Hackerrank_problems/Triangle_Quest_2/Problem.md, Hackerrank_problems/Triangle_Quest_2/Solution.py
I have made a PR for solution of  Hackerrank problem of Triangle Quest 2 in python.
@Vishruth-S Please merge my PR.
=> Added solution to the Hackerrank problem of Triangle Quest 2 in python

Hackerrank_problems/Summing_n_series/problem.md, Hackerrank_problems/Summing_n_series/solution.py
=> adding solution for summing_n_series

Hackerrank_problems/Is This a Binary Search Tree/problem.md, Hackerrank_problems/Is This a Binary Search Tree/solution.py, Hackerrank_problems/Queue using Two Stacks/problem.md, Hackerrank_problems/Queue using Two Stacks/solution.py
I have added two new problems from Hackerrank. The solution is in python, if you see something out of the standard here please let me know. Thanks in advance.
=> Add two new hackerrank problems

Hackerrank_problems/Sherlock_and_Permutation/problem.md, Hackerrank_problems/Sherlock_and_Permutation/solution.py
=> add solution for sherlock and permutation

Hackerrank_problems/Restaurant/problem.md, Hackerrank_problems/Restaurant/solution.c++
=> add restaurant solutions

Hackerrank_problems/Operators/Problem.md, Hackerrank_problems/Operators/Solution.cpp
=> New problem

Codeforces_problems/Good_Number/problem.md, Codeforces_problems/Good_Number/solution.cpp
=> Solution to a codeforces problem in c++

Codeforces_problems/Number Game/problem.md, Codeforces_problems/Number Game/solution.py
=> Add Number Game in Codeforces_problems

HackerEarth_problems/Micro and Array Update/problem.md, HackerEarth_problems/Micro and Array Update/solution.py
- [x ] My Pull Request adheres to the Contribution guidelines.
- [x ] I have added `problem.md` and `solution` files in the appropriate folder
- [ x] In `problem.md` I have provided a correct link to the problem.  
- [x ] My solution passes all the testcases within the given constraints.
- [x ] I have properly indented and documented my solution using comments.
If any of the above is unmarked, please make the necessary changes and then mark them so that you're PR can be …
=> New problem added

InterviewBit_problems/Math_Section/Problem.md, InterviewBit_problems/Math_Section/Solution.cpp
- [x ] My Pull Request adheres to the Contribution guidelines.
- [ x] I have added `problem.md` and `solution` files in the appropriate folder
- [ x] In `problem.md` I have provided a correct link to the problem.  
- [x ] My solution passes all the testcases within the given constraints.
- [ x] I have properly indented and documented my solution using comments.
If any of the above is unmarked, please make the necessary changes and then mark them so that you're PR can be …
=> Added InterviewBit Problem from maths section

USEFUL_RESOURCES.md
=> Added Useful Resources for Competitive Coding

Hackerrank_problems/Big_Sorting/problem.md, Hackerrank_problems/Big_Sorting/solution.py
=> Added Python Solution

CodeChef_problems/POTATOES/Problem.md, CodeChef_problems/POTATOES/Solution.cpp, InterviewBit_problems/EncodingBased problem/Problem.md, InterviewBit_problems/EncodingBased problem/Solution.cpp, InterviewBit_problems/Math_Section/Problem_2.md, InterviewBit_problems/Math_Section/Solution_2.cpp, InterviewBit_problems/Trees_Section/Problem.md, InterviewBit_problems/Trees_Section/Solution.cpp
=> A CP problem which helps understand and implement the prime number concept.

Hackerrank_problems/Halloween Party/problem.md, Hackerrank_problems/Halloween Party/solution.py
=> add solution for halloween party

LeetCode_problems/Range addition II/problem.md, LeetCode_problems/Range addition II/solution.cpp
=> Range Addition- leetcode problem

Codeforces_problems/Minimum Ternary String/problem.md, Codeforces_problems/Minimum Ternary String/soultion.cpp
=> add codeforces problem Minimum Ternary String level-B

Hackerrank_problems/Bitwise_operator/PROBLEM.md, Hackerrank_problems/Bitwise_operator/SOLUTION.c
=> Bitwise operator ques hackerrank

LeetCode_problems/UniqueMorseCode/problem.md, LeetCode_problems/UniqueMorseCode/solution.cpp
=> solution for unique morse code q added, solved

USEFUL_RESOURCES.md
=> Added Coding Resources and mock interview websites

LeetCode_problems/DecryptStringFromAlphabetToInteger/problem.md, LeetCode_problems/DecryptStringFromAlphabetToInteger/solution.cpp
=> solution for decrypt string q added, solved -> 100% better than other solutions

Hackerrank_problems/If-Else/problem.md, Hackerrank_problems/If-Else/solution.java
- [X ] My Pull Request adheres to the **Contribution guidelines**.
- [X ] I have added `problem.md` and `solution` files in the **appropriate folder**.
- [ X] In `problem.md` I have provided a **correct link** to the problem.  
- [ X] The solution I have given is my **own** and not plagiarized in any form.
- [ X] My solution passes all the testcases within the given constraints.
- [X ] I have properly indented and **documented my solution using comments**.
- [ X] *I agree …
=> Please commit this new hackerrank problem of If-Else in Java

Hackerrank_problems/Intro to Conditional Statements/problem.md, Hackerrank_problems/Intro to Conditional Statements/solution.cpp
=> New prob added

LeetCode_problems/Longest Substring Without Repeating Characters/Problem.md, LeetCode_problems/Longest Substring Without Repeating Characters/Solution.cpp
=> Longest Substring Without Repeating Characters

HackerEarth_problems/Edges on a path/problem.md, HackerEarth_problems/Edges on a path/solution.py
=> Added solution for Edges on a path problem in hacker earth

LeetCode_problems/XOR Operation in an Array/problem.md, LeetCode_problems/XOR Operation in an Array/solution.py
=> added solution for leetcode 1486

Codeforces_problems/ABBB/problem.md, Codeforces_problems/ABBB/soultion.cpp
=> add new codeforces problem

LeetCode_problems/Binary_Tree_level_Order_Traversal/problem.md, LeetCode_problems/Binary_Tree_level_Order_Traversal/sol.java
=> Added Binary tree level order traversal solution (leetcode 102)

USEFUL_RESOURCES.md
=> Added useful resource for interviews

LeetCode_problems/Defanging an IP Address/problem.md, LeetCode_problems/Defanging an IP Address/solution.py
=> added solution for leetcode 1108

LeetCode_problems/Running Sum of 1d Array/problem.md, LeetCode_problems/Running Sum of 1d Array/solution.py
=> added solution for leetcode 1480

LeetCode_problems/Jewels and Stones/problem.md, LeetCode_problems/Jewels and Stones/solution.py
=> added solution for leetcode 771

USEFUL_RESOURCES.md
=> Useful Website Resource

USEFUL_RESOURCES.md
Added a new useful resource for interview preparation.
=> New useful resource for interview preparation

CodeChef_problems/XYSTR/Solution.py
=> Codechef XYSTR Python Solution

LeetCode_problems/Next Permutation/problem.md, LeetCode_problems/Next Permutation/solution.cpp
=> next permutation

CodeChef_problems/CENS20D/problem.md, CodeChef_problems/CENS20D/solution.cpp
=> added problem and solution

CodeChef_problems/CHEFSTR1/Solution.cpp
=> C++ solution to Codechef_CHEFSTR1

Hackerrank_problems/Find Merge Point of Two Lists/problem.md, Hackerrank_problems/Find Merge Point of Two Lists/solution.py
=> Add the "Find Merge Point of Two Lists" problem

Hackerrank_problems/Hackfest2020/gameOfMaximization.cpp, Hackerrank_problems/Hackfest2020/problem.md
=> Game of Maximization problem from hackfest 2020 (Comments added)

Hackerrank_problems/BeautifulDaysAtTheMovies/solution.cpp
=> added the solution  for Hackerrank problem in c++. 

LeetCode_problems/graph clone/problem.md, LeetCode_problems/graph clone/solution.cpp, PULL_REQUEST_TEMPLATE.md
=> Clonegraph

GeeksForGeeks/Kadane's Algorithm/solution.py
=> Added Python code for Kadane's Algorithm.

USEFUL_RESOURCES.md
(Only completed checklist PRs will be reviewed)   
I have added AtCoder, InterviewBit and a couple of great tutorials to the USEFUL_RESOURCES.md file. I hope you find this useful. Thanks!
=> Added tutorials and other resources to USEFUL_RESOURCES.md 

Codeforces_problems/Remove Smallest/Problem.md, Codeforces_problems/Remove Smallest/Solution.cpp
=> Added Remove Smallest Codeforces Problem and Solution

LeetCode_problems/Winner of an Array Game/solution.cpp
Functions used:
- push_back()
- erase()
=> Added solution for C++

Hackerrank_problems/Simple Text Editor/problem.md, Hackerrank_problems/Simple Text Editor/solution.py
=> Add the "Simple Text Editor" hackerrank problem

Codeforces_problems/Boy or Girl 236A/problem.md, Codeforces_problems/Boy or Girl 236A/solution.cpp
=> Create CF236A solution

Codeforces_problems/Luxurious Houses/luxuriosHouses.md, Codeforces_problems/Luxurious Houses/problem.md, Codeforces_problems/Luxurious Houses/solutions.cpp
=> Create Luxurious Houses

Codeforces_problems/Nice Matrix/problem.md, Codeforces_problems/Nice Matrix/solution.cpp
I have written cpp code for Nice Matrix
=> "Nice Matrix" Codeforces problem

LeetCode_problems/Least Number of Unique Integers after K Removals/problem.md, LeetCode_problems/Least Number of Unique Integers after K Removals/solution.py
=> Added python code for Least Number of Unique Integers after K Removals

CSES_Problems/Distinct_Numbers/problem.md, CSES_Problems/Distinct_Numbers/solution.cpp
=> Added a Solution

Codeforces_problems/Songs Compression/SongsCompression.md, Codeforces_problems/Songs Compression/problem.md, Codeforces_problems/Songs Compression/solution.cpp
=> Create Songs Compression

Hackerrank_problems/diagonal-difference/solution.java
=> Create solution.java for hackerrank problem diagonal-difference

CodeChef_problems/Factorial/problem.md, CodeChef_problems/Factorial/solution.cpp
=> Add Factorial problem from codechef

LeetCode_problems/Count and Say/question.md, LeetCode_problems/Count and Say/solution.cpp
=> Added Count and Say (LeetCode)

CSES_Problems/Subarray Sum - I/problem.md, CSES_Problems/Subarray Sum - I/solution.cpp, CSES_Problems/Subarray Sum - II/problem.md, CSES_Problems/Subarray Sum - II/solution.cpp
=> Added two solutions.

Exercism_Problems/space_age/problem.md, Exercism_Problems/space_age/solution.js
=> javascript competition code function for calculating space age

CodeChef_problems/PTMSSNG/problem.md, CodeChef_problems/PTMSSNG/solution.cpp
=> PTMSSNG CodeChef problem and its solution

LeetCode_problems/Predict the winner/Problem.md, LeetCode_problems/Predict the winner/Solution.py
=> Predict the Winner in Python

CodeChef_problems/Multiple of 3/problem.md, CodeChef_problems/Multiple of 3/solution.cpp
=> Add multiple of 3 from codechef

CodeChef_problems/CLLCM/problem.md, CodeChef_problems/CLLCM/solution.cpp
=> added solution

Spoj_problems/ACPC10A/problem.md, Spoj_problems/ACPC10A/solution.cpp, Spoj_problems/CANDY/problem.md, Spoj_problems/CANDY/solution.cpp, Spoj_problems/NSTEPS/problem.md, Spoj_problems/NSTEPS/solution.cpp, Spoj_problems/ONP/problem.md, Spoj_problems/ONP/solution.cpp, Spoj_problems/SAMER08F/problem.md, Spoj_problems/SAMER08F/solution.cpp, USEFUL_RESOURCES.md
=> Added 5 more most solved problems of spoj

Codeforces_problems/Dominant Piranha/problem.md, Codeforces_problems/Dominant Piranha/solution.cpp
Recent codeforces question  and solution in cpp
=> Dominant Piranha

Codeforces_problems/Mike And Cellphones 689A/problem.md, Codeforces_problems/Mike And Cellphones 689A/solution.cpp
=> feat: Add solution to Mike and Cellphones Codeforces problem

LeetCode_problems/Remove Element/problem.md, LeetCode_problems/Remove Element/solution.cpp
- [ x] My Pull Request adheres to the **Contribution guidelines**.
- [x ] I have added `problem.md` and `solution` files in the **appropriate folder**.
- [x ] In `problem.md` I have provided a **correct link** to the problem.  
- [ x] The solution I have given is my **own** and not plagiarized in any form.
- [x ] My solution passes all the testcases within the given constraints.
- [x ] I have properly indented and **documented my solution using comments**.
- [ x] *I agree …
=> Added Remove Element Solution with explanation

CodeChef_problems/Lapindromes/problem.md, CodeChef_problems/Lapindromes/solution.cpp
=> Add codechef problem Lapindromes

InterviewBit_problems/LeastCommonAncestor/problem.md, InterviewBit_problems/LeastCommonAncestor/solution.cpp
=> Added Least Common Ancestor problem in interviewbit

Codeforces_problems/Love A/problem.md, Codeforces_problems/Love A/solution.cpp
=> Added problem Love A from Codeforces

CodeChef_problems/MINDSUM/problem.md, CodeChef_problems/MINDSUM/solution.cpp
=> MINDSUM : Minimize Digitsum

CodeChef_problems/Chef and Street Food/problem.md, CodeChef_problems/Chef and Street Food/solution.cpp
=> Add codechef problem Chef and Street Food

Codeforces_problems/Zero Remainder Sum/problem.md, Codeforces_problems/Zero Remainder Sum/solution.cpp
Example:  - [x] Mark me as completed  
=> Zero remainder sum added

LeetCode_problems/Spiral Matrix II/problem.md, LeetCode_problems/Spiral Matrix II/solution.java
=> added leetcoode spiral matrix 2 issue#1

USEFUL_RESOURCES.md
Example:  - [x] Mark me as completed  
=> Added more links to useful resources.

LeetCode_problems/Jewels and Stones/solution.cpp
=> Added Solution in CPP

USEFUL_RESOURCES.md
Added Competitive Programmer's Handbook
=> Updated USEFUL_RESOURCES.md by adding a book

Codeforces_problems/Chef Monokarp/problem.md, Codeforces_problems/Chef Monokarp/solution.cpp
=> Added Chef Monokarp

LeetCode_problems/Rotate Digits/problem.md, LeetCode_problems/Rotate Digits/solution.js
=> Solution rotate digits

HackerEarth_problems/benny and broken odometer/Problem.md, HackerEarth_problems/benny and broken odometer/Solution.cpp
=> Digit DP Problem

LeetCode_problems/Permutation Sequence/Problem.md, LeetCode_problems/Permutation Sequence/Solution.cpp
=> LEETCODE PROBLEM

Codeforces_problems/Next Round/solution.cpp
=> Added solution for CPP

CodeChef_problems/UNITGCD/problem.md, CodeChef_problems/UNITGCD/solution.cpp
=> Added UNITGCD CodeChef problem and its solution

Codeforces_problems/Reverse Binary Strings/problem.md, Codeforces_problems/Reverse Binary Strings/solution.py
=> Added Reverse Binary Strings (Codeforces)

CodeChef_problems/Enormous Input Test/problem.md, CodeChef_problems/Enormous Input Test/solution.cpp
=> Added solution to codechef problem INTEST

Codewars_problems/Least Larger/problem.md, Codewars_problems/Least Larger/solution.js
=> Added Least Larger folder in Codewars_problems

Codeforces_problems/Yet Another Bookshelf 1433B/solution.py
Solution for Yet Another Book Shelfs
=> Added Solution For Python

InterviewBit_problems/TwoPointers/remove_duplicate_elements_II/problem.md, InterviewBit_problems/TwoPointers/remove_duplicate_elements_II/solution.cpp
=> Added InterviewBit's Remove Duplicates from Sorted Array II Problem

LeetCode_problems/Max Area of Island/problem.md, LeetCode_problems/Max Area of Island/solution.cpp
(Only completed checklist PRs will be reviewed)   
Hey, it's a popular DFS problem. Can you merge it?
=> Max area island DFS problem

Codewars_problems/Highest and Lowest/problem.md, Codewars_problems/Highest and Lowest/solution.js
=> add Highest and Lowest folder in Codewars_problems

Codeforces_problems/Maximum GCD A/problem.md, Codeforces_problems/Maximum GCD A/solution.py
=> Added solution for Maximum GCD

Codeforces_problems/Divide It A/problem.md, Codeforces_problems/Divide It A/solution.py
=> Added Solution for Divide It

CodeChef_problems/WATMELON/problem.md, CodeChef_problems/WATMELON/solution.cpp
=> add problem link and solution to the problem Watermelon

CodeChef_problems/ATTND/problem.md, CodeChef_problems/ATTND/solution.cpp
=> add problem link and solution to AttendanceAttendance

CodeChef_problems/CHEFEZQ/problem.md, CodeChef_problems/CHEFEZQ/solution.cpp
=> Add problem link and solution to Chef and Easy Queries

CodeChef_problems/RPD/problem.md, CodeChef_problems/RPD/solution.cpp
=> add problem link and solution to problem Easy Math

CodeChef_problems/CHFINTRO/problem.md, CodeChef_problems/CHFINTRO/solution.cpp
=> add problem link and solution to problem Chef and Interactive Contestants

Codeforces_problems/A. Team/problem.md, Codeforces_problems/A. Team/solution.cpp
Addition of codeforces A. Team problem, added solution and problem.md, formated with comments.
=> Codeforces A. Team Problem

Codeforces_problems/Merge It A/problem.md, Codeforces_problems/Merge It A/solution.py
=> Added Merge It Solution

Codeforces_problems/GCD Compression B/problem.md, Codeforces_problems/GCD Compression B/solution.py
=> Added Problem GCD Compression

GeeksForGeeks/Kth_Smallest_Element/Solution3.cpp
=> Updated O(n log n) solution

Codewars_problems/Where my Anagrams At/problem.md, Codewars_problems/Where my Anagrams At/solution.js
- Add anagram problem and solutions under codewars challenge
=> Add Anagram problem under Codewars

LeetCode_problems/First Missing Positive/Solution.cpp
=> Optimized Solution using unordered map

project_euler_problems/EvenFibonacciNumbers/problem.md, project_euler_problems/EvenFibonacciNumbers/solution.cpp
=> Add Even Fibonacci Numbers problem from Project Euler

project_euler_problems/CountingSundays/problem.md, project_euler_problems/CountingSundays/solution.cpp
=> Counting sundays

project_euler_problems/SumSquareDifference/problem.md, project_euler_problems/SumSquareDifference/solution.cpp
=> Added Sum Square Difference problem from Project Euler

CodeChef_problems/AND Plus OR/problem.md, CodeChef_problems/AND Plus OR/solution.cpp, Codeforces_problems/Beautiful Matrix/problem.md, Codeforces_problems/Beautiful Matrix/solution.cpp, Codeforces_problems/XXXXX/problem.md, Codeforces_problems/XXXXX/solution.cpp
=> Adding some Codechef problems and solutions

HackerEarth_problems/13 Reasons Why/solution1.py
=> print call simplified

USEFUL_RESOURCES.md
=> Added Discord Server

GeeksForGeeks/Longest Palindrome in String/problem.md, GeeksForGeeks/Longest Palindrome in String/solution.cpp
=> Added Longest palindrome in a string problem of GeeksForGeeks

LeetCode_problems/Wriggle_Sort_2/problem.md, LeetCode_problems/Wriggle_Sort_2/solution.cpp
- [x ] I have added `problem.md` and `solution` files in the **appropriate folder**.
- [ x] In `problem.md` I have provided a **correct link** to the problem.  
- [x ] The solution I have given is my **own** and not plagiarized in any form.
- [x ] I have properly indented and **documented my solution using comments**.
- [ x] *I agree that all the above marked are true to the best of my knowledge and my PR can be closed if found otherwise.*
If any of the above is unmarked, …
=> added wriggle sort 2 -leetcode
